/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false env.d.ts` (hash: 8a5f0a6435355e6279f48a59de6f0055)
interface __BaseEnv_Env {
	AI: Ai;
	FLEET_MODEL: "@cf/zai-org/glm-4.7-flash";
	FLEET_VERSION: "0.2.2";
	CoreAgent: DurableObjectNamespace<import("./src/index").CoreAgent>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "CoreAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "FLEET_MODEL" | "FLEET_VERSION">> {}
}
